### PR TITLE
Add rake file; see if Travis will run it

### PR DESCRIPTION
**Pull request by mathpunk**

### CODE REVIEW

**Review by td-extreme — COMMENTED** [review]
Does this have to do with running `cob_spec` tests in travis??

**Comment by mathpunk** [comment]
Rake runs Fitnesse, Travis runs Rake

**Comment by td-extreme** [comment]
Okay, just wanted to make sure. 
Are we still having problems with the cob_spec tests running in travis? 
or has adding Rake fixed that?

**Comment by mathpunk** [comment]
I've had Travis running cob_spec tests for a while. What I don't know how to do is get them to run as a group of tests, with one setup and one teardown. There's a setup and teardown for every test now. I also ended up with a configuration error that prevented me from running the tests from the wiki page; I have an idea of what to try but it hasn't seemed high enough value to try to fix.

**Pull request merged**
